# Generated by Django 3.1.7 on 2021-05-17 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210518_0033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemss',
            name='user',
        ),
    ]
